apiVersion: v1
metadata:
  name: myconfigpod
kind: Pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello ${myvar}! && sleep 3600']
    env:
    - name: myvar
      valueFrom:
        configMapKeyRef:
          name: my-configmap 
          key: myKey