apiVersion: v1
metadata:
  name: myportpod
kind: Pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello kubernetes! && sleep 3600']
    ports: 
        - containerPort: 8080