apiVersion: v1
metadata:
  name: mylabelpod2
  namespace: my-ns
  labels: 
    env: test
    project: e-c
kind: Pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello kube! && sleep 3600']
    